AAE-8296 springdoc migration changes - fix acceptance tests
Alfresco/alfresco-java-sdk pull request #145
Opened 2022-04-15 14:35 UTC by jsokolowskii

2022-04-21 15:22 UTC, jesty commented on alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-lib/patch.sh
> +  -e 's/ResponseEntity<Void> getModelDiagram1/byte[] getModelContent/' \
do we have other methods with an incremental number?

2022-04-21 15:23 UTC, jesty reviewed
just a question

2022-04-21 15:35 UTC, jsokolowskii commented on alfresco-apa-java-rest-api/alfresco-apa-java-rest-api-lib/patch.sh
> +  -e 's/ResponseEntity<Void> getModelDiagram1/byte[] getModelContent/' \
Yes, there are other methods (not with this name) that also have numbers.

2022-04-22 10:56 UTC, jesty approved these changes
LGTM

2022-04-22 10:58 UTC, jesty requested changes
please change version from 5.1.5-SNAPSHOT to 5.2.0-SNAPSHOT

2022-04-22 11:02 UTC, jesty approved these changes

2022-04-22 11:18 UTC, merged